name: Deploy Coderagion Cloud Monitor Web UI
on: 
  push:
    branches: 
      - dev
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: dev
    steps:
      - run: echo "Run ID ${{ github.run_id }}"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo "access key - ${{secrets.AWS_ACCESS_KEY_ID}}"
      - run: echo "access key - ${{secrets.AWS_SECRET_ACCESS_KEY}}"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Write stage to stage.txt
        run: echo "${GITHUB_REF#refs/heads/}" > branch.txt
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Log AWS version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws --version

      - name: Deploy
        env: 
          IMAGE_VERSION: "0.5.${{ github.run_number }}"      
        run: |
          npm install
          npx vite build
          cd cdk
          npm install
          npx cdk deploy --all

      - run: echo "🍏 This job's status is ${{ job.status }}."



   